
 orgs:
      - name: GTN
        domain: gtn.example.com
        msp: 
            name: gtnMSP
            id: gtnMSP

        peer:
            - name : peer0.gtn.example.com
              containerName: peer0.gtn.example.com
              location: grpc://localhost:7051
        
            - name : peer1.gtn.example.com
              containerName: peer1.gtn.example.com
              location: grpc://localhost:7056
        
        anchorPeers:
            - host: peer0.gtn.example.com
              port: 7051

        orderer:
            - orgName: Orderer
              domain: example.com
              name: orderer.example.com
              location: grpc://localhost:7050
        
        eventHub:
            peer0.gtn.example.com: grpc://localhost:7053
            
            peer1.gtn.example.com: grpc://localhost:7058
        
        ca:
            containerName: ca_peerGTN
            location: http://localhost:7054
            
        
        users: 
            - name: admin
              hostName: admin@gtn.example.com
              roles: 
                   - admin
            
            - name: User1
              hostName: User1@gtn.example.com
              roles: 
                   - member
    
      - name: Elemica
        domain: elemica.example.com
        msp: 
            name: elemicaMSP
            id: elemicaMSP

        peer:
            - name : peer0.elemica.example.com
              containerName: peer0.elemica.example.com
              location: grpc://localhost:8051
        
            - name : peer1.elemica.example.com
              containerName: peer1.elemica.example.com
              location: grpc://localhost:8056
        
        anchorPeers:
            - host: peer0.elemica.example.com
              port: 7051

        orderer:
            - orgName: Orderer
              domain: example.com
              name: orderer.example.com
              location: grpc://localhost:7050
        
        eventHub:
            peer0.elemica.example.com: grpc://localhost:8053
            
            peer1.elemica.example.com: grpc://localhost:8058
        
        ca:
            containerName: ca_peerelemica
            location: http://localhost:8054
            
        
        users: 
            - name: admin
              hostName: admin@elemica.example.com
              roles: 
                   - admin
            
            - name: User1
              hostName: User1@elemica.example.com
              roles: 
                   - member
              
              
      - name: Dun&BradStreet
        domain: dnb.example.com
        msp: 
            name: dnbMSP
            id: dnbMSP

        peer:
            - name : peer0.dnb.example.com
              containerName: peer0.dnb.example.com
              location: grpc://localhost:9051
        
            - name : peer1.dnb.example.com
              containerName: peer1.dnb.example.com
              location: grpc://localhost:9056
        
        anchorPeers:
            - host: peer0.dnb.example.com
              port: 7051

        orderer:
            - orgName: Orderer
              domain: example.com
              name: orderer.example.com
              location: grpc://localhost:7050
        
        eventHub:
            peer0.dnb.example.com: grpc://localhost:9053
            peer1.dnb.example.com: grpc://localhost:9058
        
        ca:
            containerName: ca_peerDnB
            location: http://localhost:9054
            
        
        users: 
            - name: admin
              hostName: admin@dnb.example.com
              roles: 
                   - admin
            
            - name: User1
              hostName: User1@dnb.example.com
              roles: 
                   - member

 channelDetails :
      - name: ch1
        transactionFilePath: scripts/config/ch1.tx
        orgsOnChannel: 
            - GTN
            - Elemica
            - Dun&BradStreet
                 

        